---
title: "About"
output:
  html_document: 
    toc: true
    toc_float: true
---

My full CV is available [here](downloads/amin_yakubu.pdf) <br>

### Education 
<p>**Columbia University Mailman School of Public Health '19** <br>
Master of Public Health (MPH) 
Concentration:Advanced Epidemiology 

**I.M. Sechenov First Moscow State Medical University '17**
Doctor of Medicine (MD) 
</p>

### Skills
Clinical Medicine<br>
Data Analysis<br>
Computer Statistical Learning<br> 

R <br>
SAS <br>
SQL<br>
Python (with the help of Google)


### Certification
<p>
•	SAS Certified Base Programmer for SAS 9 (Verification number: B431ETW12MBQQEKV) <br>
•	CITI Program (Human Research) <br>
•	Good Clinical Practices Certification

</p>

### Experience 

##### Graduate Research Assistant February, 2018 - Present <br>
**Database Shared Resource, Herbert Irving Comprehensive Cancer Center, Columbia University Medical Center** <br>
•	Literature review of topics of research interest <br>
•	Medical data entry of pancreatic cancer patients into Collaborative Islet Transplant Registry (CITR) <br>
•	Cleaning, matching and classifying data of pancreatic cancer patients <br>
•	Entry of adverse events associated Autologous Islet Cell Transplant procedure <br>


<p>
##### Graduate Intern - Human Research Training Program September - October, 2018                                                         
**New York City Department of Health and Mental Hygiene** <br>
Bureau of Chronic Disease Prevention and Tobacco Control <br>
Healthy Living by Design <br>
•	Conducted intercept surveys and observational studies at assigned sites prior to, and following project implementation <br>
•	Compiled and organize data and observations into an electronic database <br>
•	Assisted in data analysis and drafting of reports as needed <br>
</p>

<p>

##### Graduate Research Fellow, May – August, 2018 <br>
**Global Healthy Living Foundation, New York, NY ** <br>
•	Conducted analysis of data from various research for publications, and patient-reported outcome data to support advocacy efforts and comparative effectiveness studies using SAS <br>
•	Used statistical techniques for hypothesis testing to validate data and interpretations <br>
•	Social media (Facebook & Twitter) data mining/scrapping using Python for qualitative analysis (Sentiment analysis, word cloud) <br>
•	Successfully analyzed and interpreted PainSpot (painspot.com) data to draw conclusions for managerial data intelligence and strategy using SAS <br>
•	Assisted in the development, evaluation and dissemination of patient-centered studies related to ArthritisPower patient-powered research network <br>
•	Recruit patient, academic, and industry partners for collaborative advocacy and research initiatives
•	Independently researched health literature and journal publications to identify important patient-centered insights for select chronic illness <br>
•	Abstract writing for publication <br>

