---
title: ""
---

<br></br>

<detail> 

#### New York weather data from National Oceanic and Atmospheric Administration 

</detail>

The National Oceanic and Atmospheric Administration agency (NOAA) within the United States Department of Commerce that focuses on the conditions of the oceans, major waterways, and the atmosphere. National Centers for Environmental Information (NCEI) under NOAA provides public access to some weather data, including the GHCN (Global Historical Climatology Network)-Daily database of summary statistics from weather stations around the world

The dataset used contains the following variables.

- `id`: Weather station ID
- `date`: Date of observation
- `prcp`: Precipitation (tenths of mm)
- `snow`: Snowfall (mm)
- `snwd`: Snow depth (mm)
- `tmax`: Maximum temperature (tenths of degrees C)
- `tmin`: Minimum temperature (tenths of degrees C)

 Click [here](weather.html) to view the [dashboard](weather.html) of the visualized data.
 
 <br>The Chart A in the [dashboard](weather.html) shows the average distribution of maximum and minimum temperatures from 1981 to 2010. <br>

<br>Chart B shows the average distribution of snowfall (in inches) from 1981 to 2010 for the months of November, December, January, February and March. The chart shows that on average, there is more snowfall in January than any other month. </br>

<br>July is known to be the hottest month in New York. In chart C, we see the distribution of average maximum and minimun temperature for the month of July from 1981 - 2018. We see a cyclical pattern for both maximum and minimum temperatures for the month of July. </br>

