---
title: "NY NOAA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
library(ggridges)

```

```{r}

data("ny_noaa")

set.seed(1)

noaa_df = ny_noaa %>% 
  mutate(month = months.Date(date, abbreviate = TRUE),
         day = chron::days(date),
         year = chron::years(date),
         tmax = (as.numeric(tmax))/10,
         tmin = (as.numeric(tmin))/10,
         prcp = prcp/10,
         snow = snow/25.4)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Heatmap showing the distribution of maximum and minimum temperatures from 1981 - 2010

```{r}
hex = ggplot(noaa_df, aes(x = tmin, y = tmax)) +
  geom_hex(aes()) +
  theme(legend.position = "right") + 
  labs(
    x = "Minimum temperature (C)",
    y = "Maximum temperature (C)",
    caption = "NOAA 2017"
  )

ggplotly(hex)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Average distribution of snowfall from 1981 - 2010

```{r}
my_boxes = noaa_df %>% 
  filter(month %in% c("Nov", "Dec", "Jan", "Feb", "Mar")) %>% 
  mutate(month = forcats::fct_relevel(month, c("Nov", "Dec", "Jan", "Feb", "Mar"))) %>% 
  group_by(year, month) %>% 
  summarize(average_snow = mean(snow, na.rm = TRUE)) %>% 
  ggplot(aes(x = month, y = average_snow, fill = month)) + geom_boxplot() +
  theme(legend.position = "none") + 
  labs(
    x = "Year",
    y = "Average snowfall (in)"
  ) + viridis::scale_fill_viridis(discrete = TRUE)

ggplotly(my_boxes)
```

### Chart C: Average Maximum and Minimun temperature for the month of July from 1981 - 2018

```{r}
jul = noaa_df %>% 
  filter(month %in% c("Jul")) %>% 
  group_by(year, month) %>% 
  summarize(average_max_temp = mean(tmax, na.rm = TRUE),
            average_min_temp = mean(tmin, na.rm = TRUE)) %>% 
  gather(key = statistic, value = value, average_max_temp:average_min_temp) %>% 
  ggplot(aes(x = year, y = value, color = statistic, group = statistic)) + geom_point() + 
  theme( 
        axis.text.x = element_text(angle = 80, hjust = 1, size = 8)) + viridis::scale_color_viridis(discrete = TRUE)

ggplotly(jul)
```

